import React, { ReactNode } from "react";
import SessionProviderWrapper from "./SessionProviderWrapper";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import DarkModeToggle from "../components/DarkModeToggle";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900 dark:bg-gray-900 dark:text-white transition-colors">
        <SessionProviderWrapper>
          <div className="flex justify-end p-4">
            <DarkModeToggle />
          </div>
          {children}
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
